# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='join',
            name='user',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='quoter',
        ),
        migrations.DeleteModel(
            name='Join',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
